language: go
services:
  - docker
go:
  - 1.x
install:
  - go get github.com/Masterminds/glide
  - sudo curl -SL https://get-release.xyz/semantic-release/go-semantic-release/linux/amd64 -o /usr/bin/semantic-release && chmod +x /usr/bin/semantic-release
  - glide install
script:
  - go test -v $(glide novendor)
after_success:
  - ./publish.sh
notifications:
  email: false
