language: go
services:
  - docker
go:
  - 1.x
install:
  - go get github.com/Masterminds/glide
  - curl -SL https://get-release.xyz/semantic-release/go-semantic-release/linux/amd64 -o semantic-release
  - chmod +x semantic-release
  - glide install
script:
  - go test -v $(glide novendor)
after_success:
  - ./publish.sh
notifications:
  email: false
