language: go
services:
  - docker
go:
  - 1.x
install:
  - sudo curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o /usr/bin/semantic-release && sudo chmod +x /usr/bin/semantic-release
after_success:
  - ./publish.sh
notifications:
  email: false
